# Tentang Matriks dan NumPy
Matriks merupakan konsep matematis yang menjadi salah satu dasar operasi pada *Machine Learning* (ML). Untuk itu, sebelum mempelajari lebih lanjut penerapan ML menggunakan Python disarankan terlebih dahulu mempelajari tentang komputasi Matriks.

Komputasi matriks dengan Python menjadi lebih mudah, karena Python menyediakan sebuah library yang mampu menangani komputasi ini dengan baik yaitu Numpy.

NumPy adalah paket dasar yang digunakan untuk *scientific computing* pada Python. NumPy merupakan library yang menyediakan objek *array* multidimensi, serta berbagai objek turunannya seperti *masked array* dan matriks.

# Membuat Matriks

In [1]:
# Memanggil NumPy
# Import numpy library
import numpy as np

In [2]:
# Membuat Array
A = np.array([3,5,7])
A

array([3, 5, 7])

In [3]:
# Melihat dimensi array (jumlah kolom dan baris)
A.shape

(3,)

In [4]:
# Melihat type data pada matriks
A.dtype

dtype('int32')

In [5]:
# Contoh membuat array 2 dimensi
B = np.array([[8.2, 7.5, 6], [4, 3.5, 3]])
B

array([[8.2, 7.5, 6. ],
       [4. , 3.5, 3. ]])

In [6]:
# Melihat dimensi array
B.shape

(2, 3)

In [7]:
# Melihat type data
B.dtype

dtype('float64')

In [8]:
# Contoh membuat matrik
A = np.array([[2, 4], [5, 8], [7, 2]])
A

array([[2, 4],
       [5, 8],
       [7, 2]])

# Elemen Matriks
Elemen matriks adalah isi dari suatu matriks. Jumlah elemen dalam suatu matriks sama dengan perkalian antara jumlah kolom dengan jumlah baris.

In [9]:
# Contoh
A = np.array([[2, 4], [5, 8], [7, 2]])
print("Matrik A: ")
A

Matrik A: 


array([[2, 4],
       [5, 8],
       [7, 2]])

In [10]:
# Contoh melihat matriks A elemen baris 3 kolom 2, index array dimulai dari 0
print("Elemen Matrik baris 3 kolom 2:")
A[2,1]

Elemen Matrik baris 3 kolom 2:


2

# Operasi Matriks

## Penjumlahan Matriks
Operasi penjumlahan matriks yang dimaksud pada bagian ini adalah penjumlahan dua buah matriks dengan menjumlahkan komponen-komponen yang seletak.

In [11]:
# Contoh
A = np.array([[2, 4], [5, 8], [7, 2]])
A

array([[2, 4],
       [5, 8],
       [7, 2]])

In [12]:
B = np.array([[1, 3], [2, 4], [5, 2]])
B

array([[1, 3],
       [2, 4],
       [5, 2]])

In [13]:
# Penjumlahan matriks
A + B

array([[ 3,  7],
       [ 7, 12],
       [12,  4]])

In [14]:
A + 10

array([[12, 14],
       [15, 18],
       [17, 12]])

## Pengurangan Matriks
Operasi pengurangan dua buah matriks dilakukan dengan mengurangkan komponen-komponennya yang seletak

In [15]:
# Pengurangan matriks
A - B

array([[1, 1],
       [3, 4],
       [2, 0]])

## Perkalian dang Pembagian Matriks
Operasi perkalian dua buah matriks skalar, dilakukan dengan mengalikan semua elemen matriks dengan skalarnya. Demikian juga dengan operasi pembagian.

In [16]:
# Perkalian matriks dengan angka tertentu
A * 10

array([[20, 40],
       [50, 80],
       [70, 20]])

In [17]:
# Perkalian 2 buah matriks
A * B

array([[ 2, 12],
       [10, 32],
       [35,  4]])

In [18]:
# Pembagian matriks
A / 2

array([[1. , 2. ],
       [2.5, 4. ],
       [3.5, 1. ]])

In [19]:
# Pembagian matrik
A / B

array([[2.        , 1.33333333],
       [2.5       , 2.        ],
       [1.4       , 1.        ]])

## Operasi Sum
Digunakan untuk menjumlahkan semua elemen

In [20]:
A = np.array([[2, 4], [5, 8], [7, 2]])
A

array([[2, 4],
       [5, 8],
       [7, 2]])

In [21]:
# sum untuk semua elemen
np.sum(A)

28

In [22]:
# sum elemen axix
np.sum(A, axis=0)

array([14, 14])

In [23]:
np.sum(A, axis=1)

array([ 6, 13,  9])

## Operasi Transpose

In [24]:
A.T

array([[2, 5, 7],
       [4, 8, 2]])

# Operasi Statistik Dasar

In [25]:
# Mean(Rata-Rata)
nilai = np.array([7, 6, 8, 9, 5])
np.mean(nilai)

7.0

In [26]:
# Median(Nilai Tengah)
nilai = np.array([7, 6, 8, 9, 5])
np.mean(nilai)

7.0

In [27]:
# Standar Deviasi
nilai = np.array([7, 6, 8, 9, 5, 7, 6, 7, 4, 3])
np.std(nilai)

1.7204650534085253

In [28]:
# Nilai minimum
nilai = np.array([7, 6, 8, 9, 5, 7, 6, 7, 4, 3])
np.min(nilai)

3

In [29]:
# Nilai maksimum
nilai = np.array([7, 6, 8, 9, 5, 7, 6, 7, 4, 3])
np.max(nilai)

9